package pers.congcong.myBatis2.test.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table conutry
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Conutry {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conutry.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conutry.countryname
     *
     * @mbg.generated
     */
    private String countryname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conutry.conutrycode
     *
     * @mbg.generated
     */
    private String conutrycode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conutry.id
     *
     * @return the value of conutry.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conutry.id
     *
     * @param id the value for conutry.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conutry.countryname
     *
     * @return the value of conutry.countryname
     *
     * @mbg.generated
     */
    public String getCountryname() {
        return countryname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conutry.countryname
     *
     * @param countryname the value for conutry.countryname
     *
     * @mbg.generated
     */
    public void setCountryname(String countryname) {
        this.countryname = countryname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conutry.conutrycode
     *
     * @return the value of conutry.conutrycode
     *
     * @mbg.generated
     */
    public String getConutrycode() {
        return conutrycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conutry.conutrycode
     *
     * @param conutrycode the value for conutry.conutrycode
     *
     * @mbg.generated
     */
    public void setConutrycode(String conutrycode) {
        this.conutrycode = conutrycode;
    }
}